#!/bin/bash

# export .env 
export $(grep -v '^#' .env | xargs)

# ask how many clients
read -p "How many client containers do you want to run? " clients

# bring up container using ngfw.yml
docker-compose -f $REPO/mfw.yml up --scale mfw_traffic=$clients -d
